project_name = "Coiner"
project_version = "2.5.4"

[app]
host_visible = false
video_source = "pexels"
pexels_api_keys = [ "Ra5z3Yw0ZUwPy6Y7DddvQTgPq8lgW1JePJu1oSDJWVvrxm6R5LBwqv0x", "OWKfbDqi48tpPqaPyJVQga7FwquH1SXDtMYULID8MPU0z6krtQJ9OwZ6",]
pixabay_api_keys = [ "54923197-cd28f5e7418eaabd03cdd2edb",]
llm_provider = "deepseek"
stop_on_api_failure = true
pollinations_api_key = ""
pollinations_base_url = "https://pollinations.ai/api/v1"
pollinations_model_name = "openai-fast"
ollama_base_url = "http://host.docker.internal:11434/v1"
ollama_model_name = "qwen:7b"
openai_api_key = ""
openai_base_url = ""
openai_model_name = "gpt-4o-mini"
moonshot_api_key = "sk-0b0650da992d4c86837fdb2ebb39f30c"
moonshot_base_url = "https://api.moonshot.cn/v1"
moonshot_model_name = "moonshot-v1-8k"
oneapi_api_key = ""
oneapi_base_url = ""
oneapi_model_name = ""
g4f_model_name = "gpt-3.5-turbo"
azure_api_key = ""
azure_base_url = ""
azure_model_name = "gpt-35-turbo"
azure_api_version = "2024-02-15-preview"
gemini_api_key = ""
gemini_model_name = "gemini-1.0-pro"
qwen_api_key = ""
qwen_model_name = "qwen-max"
deepseek_api_key = "sk-0b0650da992d4c86837fdb2ebb39f30c"
deepseek_base_url = "https://api.deepseek.com"
deepseek_model_name = "deepseek-chat"
modelscope_api_key = ""
modelscope_base_url = "https://api-inference.modelscope.cn/v1/"
modelscope_model_name = "Qwen/Qwen3-32B"
subtitle_provider = "edge"
endpoint = ""
material_directory = ""
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""
max_concurrent_tasks = 1
ollama_api_key = "123"
use_gpu = true
video_quality = "ultra"
video_bitrate = "20M"
video_brightness = 1.15
video_contrast = 1.05
video_concat_mode = "random"
video_transition_mode = "none"
video_aspect = "portrait_3_4"
video_clip_duration = 3
video_count = 2
silence_duration = 0.5
console_log_level = "INFO"
video_style = "none"
intro_video_bg_type = "blurred"
intro_video_bg_blur = 48
intro_video_bg_color = "black"

[whisper]
model_size = "large-v3"
device = "GPU"
compute_type = "int8"

[proxy]

[azure]
speech_key = ""
speech_region = ""

[siliconflow]
api_key = "sk-ehmjzsdqlcbsswaplkgzjsqjrlwyjquczplhjxoszbhdjgvn"

[ui]
hide_log = false
language = "zh"
tts_server = "qwen-tts"
voice_name = "qwen|Elias|墨讲师-Female||"
voice_volume = 1.8
voice_rate = 1
bgm_type = "random"
bgm_volume = 0.1
subtitle_enabled = true
subtitle_position = "custom"
subtitle_custom_position = 90
subtitle_margin = 0.02
subtitle_auto_fit = true
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "rgba(9, 240, 101, 0.95)"
text_background_color = true
font_size = 10
stroke_color = "#000000"
stroke_width = 1.5
output_bg_color = "blue"
title_enabled = true
title_text = "骨盐含量真重要？"
title_duration = 5
title_font_name = "MicrosoftYaHeiBold.ttc"
title_font_size = 92
title_text_color = "#FFFFFF"
title_stroke_color = "#808080"
title_stroke_width = 8.5
title_background_color = "transparent"
title_position = "top"
title_margin = 0.15
title_margin_left = 0.05
title_margin_right = 0.05
title_animation = "fade_out"
title_animation_duration = 0.3
title_background_overlay = true
title_overlay_color = "rgba(10, 10, 240, 0.98)"
title_style = ""
title_align = "center"

[coze]
api_key = "sat_5QQV8lPJCo1uK0cMUsMwQMDqPUFHAVajSQnICchJYcSwmp6cuA7MAeRd73k48m4A"

[qwen]
api_key = "sk-79f1b2aa20a942b4be3933e383ad5709"

[imagemagick]
imagemagick_path = "D:\\ProgramData\\ImageMagick-7.1.12-Q16\\magick.exe"
