project_name = "MoneyPrinterTurboCN"
project_version = "1.2.66.36"

[app]
video_source = "pexels"
hide_config = false
pexels_api_keys = [ "Ra5z3Yw0ZUwPy6Y7DddvQTgPq8lgW1JePJu1oSDJWVvrxm6R5LBwqv0x", "OWKfbDqi48tpPqaPyJVQga7FwquH1SXDtMYULID8MPU0z6krtQJ9OwZ6",]
pixabay_api_keys = [ "54923197-cd28f5e7418eaabd03cdd2edb",]
llm_provider = "deepseek"
stop_on_api_failure = true
pollinations_api_key = ""
pollinations_base_url = "https://pollinations.ai/api/v1"
pollinations_model_name = "openai-fast"
ollama_base_url = "http://host.docker.internal:11434/v1"
ollama_model_name = "qwen:7b"
openai_api_key = ""
openai_base_url = ""
openai_model_name = "gpt-4o-mini"
moonshot_api_key = "sk-0b0650da992d4c86837fdb2ebb39f30c"
moonshot_base_url = "https://api.moonshot.cn/v1"
moonshot_model_name = "moonshot-v1-8k"
oneapi_api_key = ""
oneapi_base_url = ""
oneapi_model_name = ""
g4f_model_name = "gpt-3.5-turbo"
azure_api_key = ""
azure_base_url = ""
azure_model_name = "gpt-35-turbo"
azure_api_version = "2024-02-15-preview"
gemini_api_key = ""
gemini_model_name = "gemini-1.0-pro"
qwen_api_key = ""
qwen_model_name = "qwen-max"
deepseek_api_key = "sk-0b0650da992d4c86837fdb2ebb39f30c"
deepseek_base_url = "https://api.deepseek.com"
deepseek_model_name = "deepseek-chat"
modelscope_api_key = ""
modelscope_base_url = "https://api-inference.modelscope.cn/v1/"
modelscope_model_name = "Qwen/Qwen3-32B"
subtitle_provider = "edge"
endpoint = ""
material_directory = ""
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""
max_concurrent_tasks = 1
ollama_api_key = "123"
use_gpu = true
video_quality = "ultra"
video_bitrate = "20M"
video_brightness = 1.15
video_contrast = 1.05
video_concat_mode = "sequential"
video_transition_mode = "none"
video_aspect = "portrait_3_4"
video_clip_duration = 3
video_count = 1
video_style = "none"

[whisper]
model_size = "large-v3"
device = "GPU"
compute_type = "int8"

[proxy]

[azure]
speech_key = ""
speech_region = ""

[siliconflow]
api_key = "sk-ehmjzsdqlcbsswaplkgzjsqjrlwyjquczplhjxoszbhdjgvn"

[ui]
hide_log = false
language = "zh"
tts_server = "coze-tts"
voice_name = "coze|7468512265151741979|擎苍-Male|https://lf26-appstore-sign.oceancloudapi.com/ocean-cloud-tos/VolcanoSystemVoice/zh_male_qingcang_mars_bigtts.mp3?lk3s=da27ec82&x-expires=1779327500&x-signature=%2BIySpRsmqtBDfMx8KV%2BYW2G%2Fm80%3D|无语，擎天之巨首，揽尽世间风云变幻，诸般阻碍，不过是无脉相巅峰之基石。今日之儒，来日必当十倍奉还。 无知威名，必将震慑四海八荒。|"
voice_volume = 1.2
voice_rate = 1
bgm_type = "random"
bgm_volume = 0.1
subtitle_enabled = true
subtitle_position = "custom"
subtitle_custom_position = 75
subtitle_margin = 0.05
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "rgb(234, 23, 216)"
text_background_color = true
font_size = 60
stroke_color = "#000000"
stroke_width = 1.5

[coze]
api_key = "sat_5QQV8lPJCo1uK0cMUsMwQMDqPUFHAVajSQnICchJYcSwmp6cuA7MAeRd73k48m4A"

[imagemagick]
imagemagick_path = "D:\\ProgramData\\ImageMagick-7.1.12-Q16\\magick.exe"
