x-common-volumes: &common-volumes
  - ./config.toml:/MoneyPrinterTurbo/config.toml
  - ./storage:/MoneyPrinterTurbo/storage

services:
  webui:
    image: ghcr.io/harry0703/moneyprinterturbo:latest
    container_name: "moneyprinterturbo-webui"
    ports:
      - "127.0.0.1:8501:8501"
    command: [ "streamlit", "run", "./webui/Main.py", "--server.address=0.0.0.0", "--server.port=8501", "--browser.serverAddress=127.0.0.1", "--server.enableCORS=True", "--browser.gatherUsageStats=False", "--server.showEmailPrompt=False" ]
    volumes: *common-volumes
    restart: always
  api:
    image: ghcr.io/harry0703/moneyprinterturbo:latest
    container_name: "moneyprinterturbo-api"
    ports:
      - "127.0.0.1:8080:8080"
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    restart: always
