name: 🐛 Bug Report
description: Report an error or unexpected behavior
title: "[Bug]: "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        **Before submitting an issue, please make sure you've read the following documentation: [Getting Started (English)](https://github.com/amine9812/MoneyPrinterTurbo/blob/main/README.md#system-requirements-) or [快速开始 (Chinese)](https://github.com/amine9812/MoneyPrinterTurbo/blob/main/README-zh.md).**

  - type: textarea
    attributes:
      label: Current Behavior
      description: |
        Describe the issue you're experiencing
      placeholder: |
        When I perform..., the program shows...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Describe in detail how to reproduce this issue
      placeholder: |
        1. Open...
        2. Click on...
        3. Error occurs...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error Logs
      description: |
        Please provide any error messages or logs (be careful not to include sensitive information)
      placeholder: |
        Error messages, logs, or screenshots...
    validations:
      required: true
  - type: input
    attributes:
      label: Python Version
      description: |
        The Python version you're using
      placeholder: v3.13.0, v3.10.0, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: |
        Your operating system information
      placeholder: macOS 14.1, Windows 11, Ubuntu 22.04, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: MoneyPrinterTurbo Version
      description: |
        The version of MoneyPrinterTurbo you're using
      placeholder: v1.2.2, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Any other information that might help solve the issue (screenshots, videos, etc.)
    validations:
      required: false
