name: ✨ Feature Request
description: Suggest a new idea for this project
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    attributes:
      label: Problem Statement
      description: |
        Please describe the problem you want to solve
      placeholder: |
        I encountered... when using this project
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: |
        Please describe your suggested solution or implementation
      placeholder: |
        Consider adding... feature to address this issue
    validations:
      required: true
