#!/bin/bash
# ─────────────────────────────────────────────────────────────
# Clipp Engine — Config Generator
# Writes config.toml from environment variables.
# Called by start.sh before MPT launches.
# ─────────────────────────────────────────────────────────────

set -euo pipefail

CONFIG_PATH="./config.toml"
APP_PORT="${PORT:-8080}"
APP_HOST="0.0.0.0"

cat > "$CONFIG_PATH" << TOML
# Auto-generated by generate-config.sh at container startup
# DO NOT EDIT — changes will be lost on restart

# Top-level keys — read directly by MPT's config.py
listen_host = "${APP_HOST}"
listen_port = ${APP_PORT}

[app]
host = "${APP_HOST}"
port = ${APP_PORT}
log_level = "${LOG_LEVEL:-INFO}"

[llm]
provider = "${LLM_PROVIDER:-pollinations}"
deepseek_api_key = "${DEEPSEEK_API_KEY:-}"
deepseek_base_url = "https://api.deepseek.com/v1"
deepseek_model_name = "deepseek-chat"
openai_api_key = "${OPENAI_API_KEY:-}"
openai_base_url = "https://api.openai.com/v1"
openai_model_name = "gpt-4o-mini"
gemini_api_key = "${GEMINI_API_KEY:-}"
ollama_base_url = "${OLLAMA_BASE_URL:-http://localhost:11434}"
ollama_model = "${OLLAMA_MODEL:-llama3.2}"

[video]
pexels_api_keys = ["${PEXELS_API_KEYS}"]

[security]
internal_api_secret = "${INTERNAL_API_SECRET}"

[storage]
tasks_dir = "./storage/tasks"

[voice]
default_voice = "${DEFAULT_VOICE:-en-US-AriaNeural}"
TOML

echo "config.toml generated successfully"
echo "  listen_host: ${APP_HOST}"
echo "  listen_port: ${APP_PORT}"
