#!/bin/bash
# ─────────────────────────────────────────────────────────────
# Clipp Engine — Config Generator
#
# Writes config.toml from environment variables.
# Called by start.sh before MPT launches.
# This avoids committing secrets to git while still
# giving MPT the config file it needs.
# ─────────────────────────────────────────────────────────────

set -euo pipefail

# Use template if it exists, otherwise generate from scratch
CONFIG_PATH="./config.toml"

cat > "$CONFIG_PATH" << EOF
# Auto-generated by generate-config.sh at container startup
# DO NOT EDIT - changes will be lost on restart
# Set environment variables in Railway to change settings

[app]
host = "${APP_HOST:-0.0.0.0}"
port = ${APP_PORT:-8080}
log_level = "${LOG_LEVEL:-INFO}"

[llm]
provider = "${LLM_PROVIDER:-pollinations}"
# DeepSeek (optional, high quality)
deepseek_api_key = "${DEEPSEEK_API_KEY:-}"
deepseek_base_url = "https://api.deepseek.com/v1"
deepseek_model_name = "deepseek-chat"
# OpenAI (optional)
openai_api_key = "${OPENAI_API_KEY:-}"
openai_base_url = "https://api.openai.com/v1"
openai_model_name = "gpt-4o-mini"
# Gemini (optional)
gemini_api_key = "${GEMINI_API_KEY:-}"
# Ollama (optional, for self-hosted)
ollama_base_url = "${OLLAMA_BASE_URL:-http://localhost:11434}"
ollama_model = "${OLLAMA_MODEL:-llama3.2}"

[video]
pexels_api_keys = [$(echo "${PEXELS_API_KEYS}" | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/' )]
pixabay_api_keys = [$(echo "${PIXABAY_API_KEYS:-}" | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/' )]

[security]
# Internal API secret — must match CLIPP_ENGINE_SECRET in Railway web service
internal_api_secret = "${INTERNAL_API_SECRET}"

[storage]
# Railway ephemeral disk — videos are transferred to R2 immediately after generation
tasks_dir = "./storage/tasks"

[voice]
default_voice = "${DEFAULT_VOICE:-en-US-AriaNeural}"

EOF

echo "config.toml generated successfully"
